package sweforce.vaadin.layout.style2;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.*;
import sweforce.gui.display.Display;
import sweforce.vaadin.layout.display.SingleComponentDisplay;
import sweforce.vaadin.layout.display.SplitPanelDisplay;

public class Style2Layout extends CustomComponent {

    @AutoGenerated
    private VerticalLayout mainLayout;
    @AutoGenerated
    private HorizontalSplitPanel leftRightSplitPanel;
    @AutoGenerated
    private HorizontalLayout center;
    @AutoGenerated
    private HorizontalLayout header;

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */


    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */


    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */


    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */


    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */


    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */


    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */


    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */


    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

    /**
     * The constructor should first build the main layout, set the
     * composition root and then do any custom initialization.
     * <p/>
     * The constructor will not be automatically regenerated by the
     * visual editor.
     */
    public Style2Layout() {
        buildMainLayout();
        setCompositionRoot(mainLayout);

        // TODO add user code here
        buildDisplays();
    }

    private Display headerDisplay;

    private Display centerDisplay;

    private Display leftDisplay;

    private Display rightDisplay;

    private void buildDisplays() {
        headerDisplay = new SingleComponentDisplay(header);
        centerDisplay = new SingleComponentDisplay(center);
        SplitPanelDisplay splitPanelDisplay = new SplitPanelDisplay(leftRightSplitPanel);
        leftDisplay = splitPanelDisplay.new First();
        rightDisplay = splitPanelDisplay.new Second();
    }

    public Display getHeaderDisplay() {
        return headerDisplay;
    }

    public Display getCenterDisplay() {
        return centerDisplay;
    }

    public Display getLeftDisplay() {
        return leftDisplay;
    }

    public Display getRightDisplay() {
        return rightDisplay;
    }

    @AutoGenerated
    private VerticalLayout buildMainLayout() {
        // common part: create layout
        mainLayout = new VerticalLayout();
        mainLayout.setImmediate(false);
        mainLayout.setWidth("100%");
        mainLayout.setHeight("100%");
        mainLayout.setMargin(false);

        // top-level component properties
        setWidth("100.0%");
        setHeight("100.0%");

        // header
        header = new HorizontalLayout();
        header.setStyleName("header");
        header.setImmediate(false);
        header.setWidth("100.0%");
        header.setHeight("50px");
        header.setMargin(false);
        mainLayout.addComponent(header);

        // center
        center = new HorizontalLayout();
        center.setStyleName("center");
        center.setImmediate(false);
        center.setWidth("100.0%");
        center.setHeight("100.0%");
        center.setMargin(false);
        mainLayout.addComponent(center);
        mainLayout.setExpandRatio(center, 1.0f);

        // leftRightSplitPanel
        leftRightSplitPanel = new HorizontalSplitPanel();
        leftRightSplitPanel.setStyleName("leftRight");
        leftRightSplitPanel.setImmediate(false);
        leftRightSplitPanel.setWidth("100.0%");
        leftRightSplitPanel.setHeight("100.0%");
        mainLayout.addComponent(leftRightSplitPanel);
        mainLayout.setExpandRatio(leftRightSplitPanel, 1.0f);
        return mainLayout;
    }



    public void setLeftDisplaySize(float value, Unit unit) {
        leftRightSplitPanel.setSplitPosition(value, unit);
    }


}
