/*
 * Copyright 2012 Mats Svefors
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package sweforce.vaadin.sample.secure.menu;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Button;
import com.vaadin.ui.Component;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import sweforce.gui.vaadin.VaadinView;

public class MenuViewImpl extends CustomComponent implements VaadinView, MenuActivity.MenuView {

    @AutoGenerated
    private HorizontalLayout mainLayout;
    @AutoGenerated
    private Button noroleBtn;
    @AutoGenerated
    private Button role2Btn;
    @AutoGenerated
    private Button role1Btn;

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */


    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */


    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */


    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */


    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

    /**
     * The constructor should first build the main layout, set the
     * composition root and then do any custom initialization.
     * <p/>
     * The constructor will not be automatically regenerated by the
     * visual editor.
     */
    public MenuViewImpl() {
        buildMainLayout();
        setCompositionRoot(mainLayout);

        // TODO add user code here
    }

    @AutoGenerated
    private HorizontalLayout buildMainLayout() {
        // common part: create layout
        mainLayout = new HorizontalLayout();
        mainLayout.setImmediate(false);
        mainLayout.setWidth("-1px");
        mainLayout.setHeight("100%");
        mainLayout.setMargin(false);

        // top-level component properties
        setWidth("-1px");
        setHeight("100.0%");

        // role1Btn
        role1Btn = new Button();
        role1Btn.setCaption("Role1");
        role1Btn.setImmediate(true);
        role1Btn.setWidth("-1px");
        role1Btn.setHeight("-1px");
        mainLayout.addComponent(role1Btn);

        // role2Btn
        role2Btn = new Button();
        role2Btn.setCaption("Role2");
        role2Btn.setImmediate(true);
        role2Btn.setWidth("-1px");
        role2Btn.setHeight("-1px");
        mainLayout.addComponent(role2Btn);

        // noroleBtn
        noroleBtn = new Button();
        noroleBtn.setCaption("No Role");
        noroleBtn.setImmediate(true);
        noroleBtn.setWidth("-1px");
        noroleBtn.setHeight("-1px");
        mainLayout.addComponent(noroleBtn);

        return mainLayout;
    }

    public Button getNoroleBtn() {
        return noroleBtn;
    }

    public Button getRole2Btn() {
        return role2Btn;
    }

    public Button getRole1Btn() {
        return role1Btn;
    }

    @Override
    public Component asComponent() {
        return this;
    }
}
